### ISSUE TITLE
Facebook link previews not working

### ISSUE THREAD

**Issue by renaekathleen** [Crabar/ember-social-share#10]
Facebook no longer supports sharing custom titles/descriptions/images via url parameters, see https://developers.facebook.com/blog/post/2017/06/27/API-Change-Log-Modifying-Link-Previews/ and https://developers.facebook.com/docs/sharing/reference/feed-dialog/#deprecated-params.

**Comment by Crabar** [comment]
Thanks for reporting. You are totally right - facebook sharing doesn't work now. Do you have any ideas how to deal with it?

**Comment by renaekathleen** [comment]
I don't think there is a way to fix it, since their blog entry (linked above) makes it seem like they explicitly don't want these areas customized, at least for the time being. I can submit a PR that utilizes some parameters that are still allowed (quote and hashtag), which will hopefully allow for a more robust sharing experience, even though that doesn't fix the preview issues.

**Comment by Crabar** [comment]
I will appreciate any help =).

**Comment by renaekathleen** [comment]
Can this be closed now?
