### ISSUE TITLE
Consider including share for LinkedIn?

### ISSUE THREAD

**Issue by joehubert** [Crabar/ember-social-share#5]
This addon looks useful and straightforward. Have you considered including LinkedIn in the share scope or do they make things more difficult than the others?
Thanks.

**Comment by Crabar** [comment]
I looked into a their [API](https://developer.linkedin.com/docs/share-on-linkedin#) and it not looks like a hard task. So I'll try to do it when I will have some time.

**Comment by joehubert** [comment]
Thanks very much to both of you for the addition. Looking fwd to incorporating.
