### ISSUE TITLE
Add G+

### ISSUE THREAD

**Issue by Gutorov** [Crabar/ember-social-share#7]
Hi I did a g+ implementation. But it can share the only url. If you want you can make pull request https://github.com/LumoSpark/ember-social-share/commits/master

**Comment by Crabar** [comment]
Hi!
I didn't add g+ from start exactly because it doesn't work well without appropriate metatags. So I found it useless in this addon. But as there are a people who still want to add g+ share button with all these restrictions I don't see any reasons to prevent it.

**Comment by Gutorov** [comment]
Ok, no prob) g+ works not perfect, in this case it only share url) with basics of meta)

**Comment by Gutorov** [comment]
Thank you for pull request) Do you think about convert styles to sass? Pure CSS so brutall) If you agree I can do it)

**Comment by Crabar** [comment]
Sure, I don't mind it. Could you make another PR for this?

**Comment by Gutorov** [comment]
I'm sorry, what does mean PR) pull request or project))

**Comment by Crabar** [comment]
Pull request
